---
- name: Check if terminator exists (apt)
  become: true
  ansible.builtin.stat:
    path: '/usr/bin/terminator'
  register: terminator_installed

- name: Install terminator (apt)
  become: true
  ansible.builtin.apt:
    name: terminator
    state: present
  when: not terminator_installed.stat.exists

- name: Ensures config directory exists (apt)
  ansible.builtin.file:
    path: '{{ xdg_config_home }}/terminator'
    state: directory
    owner: '{{ user_name }}'
    group: '{{ user_name }}'
    mode: 0755

- name: Copy terminator config (apt)
  ansible.builtin.copy:
    src: files/config
    dest: '{{ xdg_config_home }}/terminator/config'
    owner: '{{ user_name }}'
    group: '{{ user_name }}'
    mode: 0644
  when: overwrite_existing_files | bool

- name: Configure terminator as default terminal (apt)
  become: true
  ansible.builtin.command: update-alternatives --set x-terminal-emulator /usr/bin/terminator
  when: not terminator_installed.stat.exists
