---
- name: Check if Docker is installed
  become: true
  ansible.builtin.stat:
    path: '/usr/bin/docker'
  register: docker_installed

- name: Add Docker GPG apt Key
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  when: not docker_installed.stat.exists

- name: Add Docker Repository
  become: true
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present
  when: not docker_installed.stat.exists

- name: Install Docker
  become: true
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: latest
  when: not docker_installed.stat.exists

- name: Add Docker Group
  become: true
  ansible.builtin.group:
    name: docker
    state: present
  when: not docker_installed.stat.exists

- name: Add User to Docker Group
  become: true
  ansible.builtin.user:
    name: '{{ user_name }}'
    groups: docker
    append: yes
  when: not docker_installed.stat.exists

- name: Enable Docker Service
  become: true
  ansible.builtin.service:
    name: docker
    enabled: yes
    state: started
  when: not docker_installed.stat.exists
